# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.13-slim

# Install dependencies
WORKDIR /app
COPY pyproject.toml .
# Install build tools
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc libffi-dev make && \
    rm -rf /var/lib/apt/lists/*

# Copy source code
COPY . .

# Install the package and its dependencies
RUN pip install --no-cache-dir .

# Install dotenv support
RUN pip install --no-cache-dir python-dotenv

# Default workdir for outputs
ENV OUTPUT_DIRECTORY=.

# Default command
CMD ["cartesia-mcp"]
